### ISSUE TITLE
Game Crashing EMI not loading recipes

### ISSUE THREAD

**Issue by f0kx** [Suel-ki/FoodEffectTooltips-Forge#5]
[crash-2024-10-13_17.44.57-client.txt](https://github.com/user-attachments/files/17379237/crash-2024-10-13_17.44.57-client.txt)

After deleting the mod all was fine and also EMI was loading recipes again

Minecraft 1.19.2 forge

**Comment by Suel-ki** [comment]
Look at this [issue](https://github.com/DaFuqs/FoodEffectTooltips/issues/9).
